### ISSUE TITLE
ro-crate-metadata spreadsheet template changes

### ISSUE THREAD

**Issue by benfoley** [Language-Research-Technology/ldaca-website#38]
This issue is to collect fixes/updates/changes to the fabulous spreadsheet template and related updates to the docs.

**Comment by benfoley** [comment]
Mismatch between the id used in the EAF example `isRef_annotationOf` and the WAV's ID

```
| isRef_annotationOf
---
| ExampleCollection_Speaker_01.wav
```

Wav @ID is `Audio/ExampleCollection_Speaker_01.wav`

**Comment by rosanna-smith** [comment]
wav ids updated in new live version
