### ISSUE TITLE
ro-crate-metadata-template datePublished

### ISSUE THREAD

**Issue by benfoley** [Language-Research-Technology/ldaca-website#46]
The spreadsheet Root tab should include a `datePublished` column, with data type of the col set to `Text`, and an example date in `yyyy-mm-dd` format (eg `2024-09-04`). This is a default requirement of RO-Crate. 

Please also include info about datePublished in user guide, explaining that the cell type needs to be Text so that the tooling doesn't interpret the value as a date and do timezone conversion and other wacky things. The datePublished is typically the date that the crate was made.

**Comment by rosanna-smith** [comment]
Just checked the language data commons mode and datePublished has the type Date:
```
"id": "http://schema.org/datePublished",
"name": "datePublished",
"help": "The (earliest) date the collection protocol was published.",
"type": [
    "Date"
],
"multiple": false
```

Default simple RO-Crate mode has instances of both Text and Date types for datePublished. Do those all need to be updated to Text?

**Comment by rosanna-smith** [comment]
And in the guideline under Objects, this is the wording per Wolfgang that lines up more with the Date type:
The date the object was published. The date will be converted in [Crate-O](https://www.ldaca.edu.au/resources/glossary/#crate-o) to ISO 8601 format, e.g. Wed Jun 12 2024 10:00:00 GMT+1000 (Australian Eastern Standard Time).
