### ISSUE TITLE
/posts/ link is not there anymore

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/ldaca-website#7]
@smusgrav @otili9890 

/posts/ link is not there anymore. and some people have been linking them into other websites/documents can we have it back?

**Comment by otili9890** [comment]
Old /posts location now redirects to new locations

**Comment by moisbo** [comment]
Hi Otis -- this still doesnt work see examples:

https://www.ldaca.edu.au/posts/fair-care-eresearch-2022/

another example: https://www.ldaca.edu.au/posts/rdc-tech-meeting/

**Comment by otili9890** [comment]
Fixed, closing issue

**Comment by ptsefton** [comment]
Just reopening to ask how this was fixed @otili9890 -- don't want to accidentally undo this work in the future.

Also a note that if possible it is preferable to use permalinks for all pages -- changing the navigation on the site should not change URLs.

For future reference you could have put the old URLs for each existing post into the source https://gohugo.io/content-management/urls/#permalinks-configuration-example OR a better solution would be to set up permalinks for all posts that matched the existing structure (/post/slug) so things didn't move and new posts used the old structure.

**Comment by otili9890** [comment]
Ah okay thanks didn't realise about the permalinks, I used aliases to redirect from the old locations in the head section e.g.
`aliases: 
- "/posts/fair-and-care/"`
In future the permalinks will be the way to go

**Comment by ptsefton** [comment]
OK closing this -- next time there's a site overhaul lets talk about it in the tech team
