### ISSUE TITLE
menu is locked to a position so if someone scrolls a bit the menu is not reachable

### ISSUE THREAD

**Issue by moisbo** [Language-Research-Technology/ldaca-website#8]
menu is hardcoded to a position so if someone scrolls a bit the menu is locked in a position 

To reproduce:

- open ldaca.edu.au
- scroll so you can still see the menu
- hover the menu

See images:

<img width="920" alt="Screenshot 2024-03-06 at 3 56 45 pm" src="https://github.com/Language-Research-Technology/ldaca-website/assets/2850269/beaeef71-65d1-45c9-9032-c404a680ab5c">

![Screenshot 2024-03-06 at 3 46 52 pm](https://github.com/Language-Research-Technology/ldaca-website/assets/2850269/fe8fe90e-2c3b-4de6-922b-41fb12c3b25a)

**Comment by otili9890** [comment]
Fixed thanks to @r-tae
